spring:
  application:
    name: cloudnote
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloudnote
    username: slowhigh
    password: cloudnote1!
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: update # create-only, validate, create-drop, update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true